import type {
  Category,
  FulfillmentPartner,
  FulfillmentRequest,
  InventoryLevel,
  InventoryLocation,
  Order,
  Product,
  Promotion,
  Shipment,
} from "@/lib/types";

export const categories: Category[] = [
  {
    id: "cat_cotton",
    name: "Cotton",
    slug: "cotton",
    description: "Everyday woven and twill cottons for apparel and utility goods.",
    count: 2,
    isFeatured: true,
  },
  {
    id: "cat_linen",
    name: "Linen",
    slug: "linen",
    description: "Natural linens with a soft hand and a clean drape.",
    count: 1,
    isFeatured: true,
  },
  {
    id: "cat_performance",
    name: "Performance",
    slug: "performance",
    description: "Durable textiles for activewear, workwear, and technical products.",
    count: 1,
    isFeatured: true,
  },
  {
    id: "cat_decorative",
    name: "Decorative",
    slug: "decorative",
    description: "Border fabrics, trims, and statement textiles for special applications.",
    count: 1,
    isFeatured: false,
  },
  {
    id: "cat_tailoring",
    name: "Tailoring",
    slug: "tailoring",
    description: "Structured blends for jackets, suiting, and premium apparel.",
    count: 1,
    isFeatured: false,
  },
];

export const products: Product[] = [
  {
    id: "prod_indigo_twill",
    slug: "indigo-loom-cotton-twill",
    name: "Indigo Loom Cotton Twill",
    description:
      "Dense midweight cotton twill for utility shirts, aprons, uniforms, and structured apparel.",
    categorySlug: "cotton",
    categoryName: "Cotton",
    material: "100% cotton",
    weave: "Twill",
    color: "Indigo",
    width: "54 in",
    unitType: "yard",
    unitIncrement: 1,
    price: 18.5,
    compareAtPrice: 24,
    stockQty: 840,
    minimumOrderQty: 2,
    badge: "Best Seller",
    shipbobReferenceId: "TL-INDIGO-TWILL",
    visualTone: "indigo",
    status: "active",
    featured: true,
    specs: ["Midweight", "Reactive dye", "Cut-to-order", "Pre-shrunk"],
    dealNote: "Eligible for the Spring Loom Event discount.",
  },
  {
    id: "prod_sandstone_linen",
    slug: "sandstone-linen-canvas",
    name: "Sandstone Linen Canvas",
    description:
      "Airy linen canvas with a crisp finish for home goods, relaxed tailoring, and elevated basics.",
    categorySlug: "linen",
    categoryName: "Linen",
    material: "85% linen, 15% cotton",
    weave: "Canvas",
    color: "Sandstone",
    width: "58 in",
    unitType: "yard",
    unitIncrement: 1,
    price: 22,
    compareAtPrice: 28,
    stockQty: 510,
    minimumOrderQty: 2,
    badge: "New Arrival",
    shipbobReferenceId: "TL-SANDSTONE-LINEN",
    visualTone: "sand",
    status: "active",
    featured: true,
    specs: ["Stonewashed", "Breathable", "Cut-to-order", "Low-lint"],
    dealNote: "Pairs well with wholesale starter pricing.",
  },
  {
    id: "prod_evergreen_performance",
    slug: "evergreen-recycled-performance-weave",
    name: "Evergreen Recycled Performance Weave",
    description:
      "Moisture-resistant recycled blend for activewear, travel gear, and durable lifestyle products.",
    categorySlug: "performance",
    categoryName: "Performance",
    material: "Recycled polyester blend",
    weave: "Performance weave",
    color: "Evergreen",
    width: "60 in",
    unitType: "yard",
    unitIncrement: 1,
    price: 16,
    compareAtPrice: 20,
    stockQty: 780,
    minimumOrderQty: 3,
    badge: "Eco Line",
    shipbobReferenceId: "TL-EVERGREEN-PERFORMANCE",
    visualTone: "sage",
    status: "active",
    featured: true,
    specs: ["Moisture resistant", "Quick dry", "Low stretch", "Cut-to-order"],
  },
  {
    id: "prod_ember_jacquard",
    slug: "ember-jacquard-border",
    name: "Ember Jacquard Border",
    description:
      "Decorative jacquard border textile for premium accents, trims, and special collections.",
    categorySlug: "decorative",
    categoryName: "Decorative",
    material: "Poly-cotton blend",
    weave: "Jacquard",
    color: "Ember",
    width: "45 in",
    unitType: "yard",
    unitIncrement: 1,
    price: 27,
    compareAtPrice: 32,
    stockQty: 210,
    minimumOrderQty: 1,
    badge: "Limited",
    shipbobReferenceId: "TL-EMBER-JACQUARD",
    visualTone: "amber",
    status: "active",
    featured: false,
    specs: ["Patterned border", "High detail weave", "Premium trim", "Limited run"],
  },
  {
    id: "prod_midnight_suiting",
    slug: "midnight-wool-suiting",
    name: "Midnight Wool Suiting",
    description:
      "Smooth tailored suiting fabric for jackets, trousers, and polished apparel programs.",
    categorySlug: "tailoring",
    categoryName: "Tailoring",
    material: "Wool blend",
    weave: "Plain weave",
    color: "Midnight",
    width: "60 in",
    unitType: "yard",
    unitIncrement: 1,
    price: 34,
    compareAtPrice: 42,
    stockQty: 120,
    minimumOrderQty: 2,
    badge: "Premium",
    shipbobReferenceId: "TL-MIDNIGHT-SUITING",
    visualTone: "ruby",
    status: "active",
    featured: true,
    specs: ["Tailoring grade", "Smooth hand", "Deep color", "Low stock"],
    dealNote: "Priority shipment available through the East Harbor 3PL route.",
  },
];

export const promotions: Promotion[] = [
  {
    id: "promo_spring_loom",
    name: "Spring Loom Event",
    description: "15% off selected cotton and linen fabrics.",
    code: "LOOM15",
    type: "percent",
    status: "active",
    discountSummary: "15% off cotton and linen styles",
    appliesTo: "Cotton + Linen categories",
    validThrough: "2026-06-30",
  },
  {
    id: "promo_wholesale_starter",
    name: "Wholesale Starter",
    description: "$50 off orders above $500 for new bulk buyers.",
    code: "WHOLESALE50",
    type: "fixed_amount",
    status: "active",
    discountSummary: "$50 off orders over $500",
    appliesTo: "Wholesale carts",
    validThrough: "2026-09-15",
  },
  {
    id: "promo_freight_free",
    name: "Freight Free Shipping",
    description: "Free shipping on qualified domestic orders.",
    code: "SHIPFREE",
    type: "free_shipping",
    status: "scheduled",
    discountSummary: "Free shipping over $150",
    appliesTo: "Domestic retail orders",
    validThrough: "2026-08-01",
  },
];

export const fulfillmentPartners: FulfillmentPartner[] = [
  {
    id: "partner_east_harbor",
    name: "East Harbor 3PL",
    integrationType: "api",
    status: "active",
    region: "Northeast",
    turnaround: "Same-day pick, next-day dock",
    contact: "ops@eastharbor3pl.example",
  },
  {
    id: "partner_metro_textile",
    name: "Metro Textile Fulfillment",
    integrationType: "csv",
    status: "active",
    region: "Mid-Atlantic",
    turnaround: "24-hour pick",
    contact: "fulfillment@metrotextile.example",
  },
  {
    id: "partner_shipbob",
    name: "ShipBob",
    integrationType: "api",
    status: "active",
    region: "National",
    turnaround: "Same-day ship on eligible SKUs",
    contact: "integrations@shipbob.example",
  },
];

export const fulfillmentRequests: FulfillmentRequest[] = [
  {
    id: "request_1048",
    orderId: "order_1048",
    orderNumber: "TX-1048",
    fulfillmentPartnerId: "partner_east_harbor",
    fulfillmentPartnerName: "East Harbor 3PL",
    inventoryLocationId: "loc_east_harbor",
    inventoryLocationName: "East Harbor 3PL",
    status: "fulfilled",
    partnerReference: "EHB-1048",
    requestPayload: {
      orderNumber: "TX-1048",
      customerName: "Maya Patel",
      destination: "Brooklyn, NY",
      itemCount: 2,
    },
    responsePayload: {
      trackingNumber: "TXT-1048",
      carrier: "UPS",
      serviceLevel: "Ground",
      accepted: true,
    },
    createdAt: "2026-06-09T15:58:00Z",
    updatedAt: "2026-06-09T16:30:00Z",
  },
  {
    id: "request_1049",
    orderId: "order_1049",
    orderNumber: "TX-1049",
    fulfillmentPartnerId: "partner_shipbob",
    fulfillmentPartnerName: "ShipBob",
    inventoryLocationId: "loc_brooklyn_stockroom",
    inventoryLocationName: "Brooklyn Stockroom",
    status: "fulfilled",
    partnerReference: "SB-1049",
    requestPayload: {
      orderNumber: "TX-1049",
      customerName: "Jordan Smith",
      destination: "Philadelphia, PA",
      itemCount: 1,
    },
    responsePayload: {
      trackingNumber: "TXT-1049",
      carrier: "FedEx",
      serviceLevel: "Home Delivery",
      accepted: true,
    },
    createdAt: "2026-06-12T12:20:00Z",
    updatedAt: "2026-06-12T13:05:00Z",
  },
  {
    id: "request_1050",
    orderId: "order_1050",
    orderNumber: "TX-1050",
    fulfillmentPartnerId: "partner_east_harbor",
    fulfillmentPartnerName: "East Harbor 3PL",
    inventoryLocationId: "loc_east_harbor",
    inventoryLocationName: "East Harbor 3PL",
    status: "accepted",
    partnerReference: "EHB-1050",
    requestPayload: {
      orderNumber: "TX-1050",
      customerName: "Acme Interiors",
      destination: "Jersey City, NJ",
      itemCount: 2,
    },
    responsePayload: {
      message: "Label created and tracking assigned.",
      trackingNumber: "TXT-1050",
      carrier: "DHL",
      serviceLevel: "Priority",
    },
    createdAt: "2026-06-13T13:42:00Z",
    updatedAt: "2026-06-13T14:10:00Z",
  },
  {
    id: "request_1051",
    orderId: "order_1051",
    orderNumber: "TX-1051",
    fulfillmentPartnerId: "partner_metro_textile",
    fulfillmentPartnerName: "Metro Textile Fulfillment",
    inventoryLocationId: undefined,
    inventoryLocationName: undefined,
    status: "failed",
    requestPayload: {
      orderNumber: "TX-1051",
      customerName: "Studio North",
      destination: "Newark, NJ",
      itemCount: 1,
    },
    responsePayload: {
      error: "Address verification failed",
    },
    createdAt: "2026-06-13T11:05:00Z",
    updatedAt: "2026-06-13T13:45:00Z",
  },
];

export const inventoryLocations: InventoryLocation[] = [
  {
    id: "loc_brooklyn_stockroom",
    name: "Brooklyn Stockroom",
    type: "warehouse",
    region: "New York",
    contact: "brooklyn-ops@example.com",
  },
  {
    id: "loc_east_harbor",
    name: "East Harbor 3PL",
    type: "3pl",
    region: "New Jersey",
    contact: "ops@eastharbor3pl.example",
  },
  {
    id: "loc_jersey_transit",
    name: "Jersey Transit Hub",
    type: "in_transit",
    region: "New Jersey",
    contact: "logistics@example.com",
  },
];

export const inventoryLevels: InventoryLevel[] = [
  {
    id: "inv_1",
    inventoryLocationId: "loc_brooklyn_stockroom",
    inventoryLocationName: "Brooklyn Stockroom",
    productId: "prod_indigo_twill",
    productName: "Indigo Loom Cotton Twill",
    variantName: "Indigo / Yard",
    onHandQty: 420,
    reservedQty: 60,
    availableQty: 360,
    lowStockThreshold: 120,
  },
  {
    id: "inv_2",
    inventoryLocationId: "loc_brooklyn_stockroom",
    inventoryLocationName: "Brooklyn Stockroom",
    productId: "prod_sandstone_linen",
    productName: "Sandstone Linen Canvas",
    variantName: "Sandstone / Yard",
    onHandQty: 270,
    reservedQty: 35,
    availableQty: 235,
    lowStockThreshold: 90,
  },
  {
    id: "inv_3",
    inventoryLocationId: "loc_east_harbor",
    inventoryLocationName: "East Harbor 3PL",
    productId: "prod_evergreen_performance",
    productName: "Evergreen Recycled Performance Weave",
    variantName: "Evergreen / Yard",
    onHandQty: 510,
    reservedQty: 95,
    availableQty: 415,
    lowStockThreshold: 150,
  },
  {
    id: "inv_4",
    inventoryLocationId: "loc_east_harbor",
    inventoryLocationName: "East Harbor 3PL",
    productId: "prod_midnight_suiting",
    productName: "Midnight Wool Suiting",
    variantName: "Midnight / Yard",
    onHandQty: 120,
    reservedQty: 14,
    availableQty: 106,
    lowStockThreshold: 80,
  },
  {
    id: "inv_5",
    inventoryLocationId: "loc_jersey_transit",
    inventoryLocationName: "Jersey Transit Hub",
    productId: "prod_ember_jacquard",
    productName: "Ember Jacquard Border",
    variantName: "Ember / Yard",
    onHandQty: 90,
    reservedQty: 10,
    availableQty: 80,
    lowStockThreshold: 30,
  },
];

export const orders: Order[] = [
  {
    id: "order_1048",
    orderNumber: "TX-1048",
    customerName: "Maya Patel",
    status: "shipped",
    paymentStatus: "captured",
    createdAt: "2026-06-08T14:22:00Z",
    total: 294,
    shippingTotal: 18,
    itemCount: 2,
    fulfillmentPartnerName: "East Harbor 3PL",
    destination: "Brooklyn, NY",
    items: [
      {
        id: "item_1048_1",
        productName: "Indigo Loom Cotton Twill",
        variantName: "Indigo / Yard",
        quantity: 12,
        unitPrice: 18.5,
        lineTotal: 222,
        shipbobReferenceId: "TL-INDIGO-TWILL",
        fulfillmentStatus: "fulfilled",
      },
      {
        id: "item_1048_2",
        productName: "Ember Jacquard Border",
        variantName: "Ember / Yard",
        quantity: 2,
        unitPrice: 27,
        lineTotal: 54,
        shipbobReferenceId: "TL-EMBER-JACQUARD",
        fulfillmentStatus: "fulfilled",
      },
    ],
  },
  {
    id: "order_1049",
    orderNumber: "TX-1049",
    customerName: "Jordan Smith",
    status: "paid",
    paymentStatus: "captured",
    createdAt: "2026-06-11T16:40:00Z",
    total: 213,
    shippingTotal: 15,
    itemCount: 1,
    fulfillmentPartnerName: "Brooklyn Stockroom",
    destination: "Philadelphia, PA",
    items: [
      {
        id: "item_1049_1",
        productName: "Sandstone Linen Canvas",
        variantName: "Sandstone / Yard",
        quantity: 9,
        unitPrice: 22,
        lineTotal: 198,
        shipbobReferenceId: "TL-SANDSTONE-LINEN",
        fulfillmentStatus: "allocated",
      },
    ],
  },
  {
    id: "order_1050",
    orderNumber: "TX-1050",
    customerName: "Acme Interiors",
    status: "allocated",
    paymentStatus: "authorized",
    createdAt: "2026-06-12T12:05:00Z",
    total: 636,
    shippingTotal: 42,
    itemCount: 2,
    fulfillmentPartnerName: "East Harbor 3PL",
    destination: "Jersey City, NJ",
    items: [
      {
        id: "item_1050_1",
        productName: "Evergreen Recycled Performance Weave",
        variantName: "Evergreen / Yard",
        quantity: 18,
        unitPrice: 16,
        lineTotal: 288,
        shipbobReferenceId: "TL-EVERGREEN-PERFORMANCE",
        fulfillmentStatus: "allocated",
      },
      {
        id: "item_1050_2",
        productName: "Midnight Wool Suiting",
        variantName: "Midnight / Yard",
        quantity: 9,
        unitPrice: 34,
        lineTotal: 306,
        shipbobReferenceId: "TL-MIDNIGHT-SUITING",
        fulfillmentStatus: "allocated",
      },
    ],
  },
  {
    id: "order_1051",
    orderNumber: "TX-1051",
    customerName: "Studio North",
    status: "exception",
    paymentStatus: "captured",
    createdAt: "2026-06-13T09:12:00Z",
    total: 127,
    shippingTotal: 16,
    itemCount: 1,
    fulfillmentPartnerName: "Metro Textile Fulfillment",
    destination: "Newark, NJ",
    items: [
      {
        id: "item_1051_1",
        productName: "Indigo Loom Cotton Twill",
        variantName: "Indigo / Yard",
        quantity: 6,
        unitPrice: 18.5,
        lineTotal: 111,
        shipbobReferenceId: "TL-INDIGO-TWILL",
        fulfillmentStatus: "backordered",
      },
    ],
    notes: "Address verification needed before release.",
  },
  {
    id: "order_1052",
    orderNumber: "TX-1052",
    customerName: "North Shore Atelier",
    status: "paid",
    paymentStatus: "captured",
    createdAt: "2026-06-15T10:18:00Z",
    total: 190,
    shippingTotal: 14,
    itemCount: 1,
    fulfillmentPartnerName: "ShipBob",
    destination: "Boston, MA",
    shippingAddress: {
      address1: "88 Seaport Blvd",
      address2: "Suite 102",
      companyName: "North Shore Atelier",
      city: "Boston",
      state: "MA",
      country: "US",
      zipCode: "02110",
      email: "ops@northshoreatelier.example",
      phoneNumber: "617-555-0148",
    },
    items: [
      {
        id: "item_1052_1",
        productName: "Sandstone Linen Canvas",
        variantName: "Sandstone / Yard",
        quantity: 8,
        unitPrice: 22,
        lineTotal: 176,
        shipbobReferenceId: "TL-SANDSTONE-LINEN",
        fulfillmentStatus: "pending",
      },
    ],
    notes: "Ready for automated fulfillment dispatch.",
  },
];

export const shipments: Shipment[] = [
  {
    id: "ship_1048",
    orderId: "order_1048",
    orderNumber: "TX-1048",
    fulfillmentRequestId: "request_1048",
    trackingNumber: "TXT-1048",
    carrier: "UPS",
    serviceLevel: "Ground",
    status: "in_transit",
    partnerName: "East Harbor 3PL",
    destination: "Brooklyn, NY",
    shippedAt: "2026-06-09T16:30:00Z",
    estimatedDeliveryAt: "2026-06-13T18:00:00Z",
    events: [
      {
        id: "event_1048_1",
        eventStatus: "label_created",
        message: "Shipping label created and transmitted to UPS.",
        eventAt: "2026-06-09T15:58:00Z",
        source: "3pl",
      },
      {
        id: "event_1048_2",
        eventStatus: "packed",
        message: "Order packed at East Harbor 3PL.",
        eventAt: "2026-06-09T16:14:00Z",
        source: "3pl",
      },
      {
        id: "event_1048_3",
        eventStatus: "in_transit",
        message: "Shipment departed the local hub.",
        eventAt: "2026-06-10T08:41:00Z",
        source: "carrier",
      },
    ],
  },
  {
    id: "ship_1049",
    orderId: "order_1049",
    orderNumber: "TX-1049",
    fulfillmentRequestId: "request_1049",
    trackingNumber: "TXT-1049",
    carrier: "FedEx",
    serviceLevel: "Home Delivery",
    status: "delivered",
    partnerName: "Brooklyn Stockroom",
    destination: "Philadelphia, PA",
    shippedAt: "2026-06-12T13:05:00Z",
    deliveredAt: "2026-06-14T10:22:00Z",
    estimatedDeliveryAt: "2026-06-14T18:00:00Z",
    events: [
      {
        id: "event_1049_1",
        eventStatus: "label_created",
        message: "FedEx label created.",
        eventAt: "2026-06-12T12:30:00Z",
        source: "3pl",
      },
      {
        id: "event_1049_2",
        eventStatus: "shipped",
        message: "Shipment left the Brooklyn Stockroom.",
        eventAt: "2026-06-12T13:05:00Z",
        source: "carrier",
      },
      {
        id: "event_1049_3",
        eventStatus: "delivered",
        message: "Delivered to receiving desk.",
        eventAt: "2026-06-14T10:22:00Z",
        source: "carrier",
      },
    ],
  },
  {
    id: "ship_1050",
    orderId: "order_1050",
    orderNumber: "TX-1050",
    fulfillmentRequestId: "request_1050",
    trackingNumber: "TXT-1050",
    carrier: "DHL",
    serviceLevel: "Priority",
    status: "label_created",
    partnerName: "East Harbor 3PL",
    destination: "Jersey City, NJ",
    shippedAt: "2026-06-13T14:10:00Z",
    estimatedDeliveryAt: "2026-06-16T18:00:00Z",
    events: [
      {
        id: "event_1050_1",
        eventStatus: "label_created",
        message: "Priority label generated for large wholesale order.",
        eventAt: "2026-06-13T14:10:00Z",
        source: "3pl",
      },
      {
        id: "event_1050_2",
        eventStatus: "packed",
        message: "Packed and staged for carrier pickup.",
        eventAt: "2026-06-13T15:02:00Z",
        source: "3pl",
      },
    ],
  },
  {
    id: "ship_1051",
    orderId: "order_1051",
    orderNumber: "TX-1051",
    fulfillmentRequestId: undefined,
    trackingNumber: "TXT-1051",
    carrier: "UPS",
    serviceLevel: "Ground",
    status: "exception",
    partnerName: "Metro Textile Fulfillment",
    destination: "Newark, NJ",
    shippedAt: "2026-06-13T11:20:00Z",
    estimatedDeliveryAt: "2026-06-17T18:00:00Z",
    events: [
      {
        id: "event_1051_1",
        eventStatus: "label_created",
        message: "Label created after allocation.",
        eventAt: "2026-06-13T11:20:00Z",
        source: "3pl",
      },
      {
        id: "event_1051_2",
        eventStatus: "exception",
        message: "Address validation failed and shipment is on hold.",
        eventAt: "2026-06-13T13:45:00Z",
        source: "customer_service",
      },
    ],
  },
];

export const siteMetrics = {
  activeSkus: products.filter((product) => product.status === "active").length,
  openOrders: orders.filter((order) =>
    ["draft", "pending_payment", "paid", "allocated", "partially_fulfilled", "exception"].includes(
      order.status
    )
  ).length,
  partnerCount: fulfillmentPartners.length,
  onTimeShipRate: 97,
};

export const featuredProducts = products.filter((product) => product.featured);
export const activePromotions = promotions.filter((promotion) => promotion.status === "active");
export const openOrders = orders.filter((order) =>
  ["draft", "pending_payment", "paid", "allocated", "partially_fulfilled", "exception"].includes(
    order.status
  )
);
export const recentShipments = shipments.slice(0, 3);

export function findProductBySlug(slug: string) {
  return products.find((product) => product.slug === slug);
}

export function findShipmentByTrackingNumber(trackingNumber: string) {
  const lookup = trackingNumber.trim().toUpperCase();
  return shipments.find((shipment) => shipment.trackingNumber.toUpperCase() === lookup);
}

export function findShipmentById(id: string) {
  return shipments.find((shipment) => shipment.id === id);
}

export function findOrderById(id: string) {
  return orders.find((order) => order.id === id);
}
